Patrick BROCKMANN<br>
Software engineer at LSCE (Climate and Environment Sciences Laboratory)<br>
<img align="left" width="40%" src="http://www.lsce.ipsl.fr/Css/img/banniere_LSCE_75.png"><br><br>
<hr>

Coded the 2015/12/09

In [1]:
import numpy as np
import pandas as pd
import collections
import os

In [120]:
# Define CSV files for sources and dividers
Sources = collections.OrderedDict()
Sources['Coal'] = 'coal.csv'
Sources['Oil']='oil.csv'   
Sources['Gas']='gas.csv'
Sources['Gas flaring']='flaring.csv'
Sources['Cement']='cement.csv'

Dividers = collections.OrderedDict()
Dividers['GDP']='gdp.csv'
Dividers['Population']='population.csv'

In [121]:
# Those regions are defined following Emissions application http://www.globalcarbonatlas.org
# Added 'Lesotho', 'Liechtenstein' that are present in csv file but not in Emissions application
# Removed 'Western Sahara' present in Emissions application but not in csv file 
# Have to define "C\xb4te d'Ivoire" 'R\xa9union' to be according with the csv file

Regions = collections.OrderedDict()

Regions['Africa'] = ['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cape Verde', 'Central African Republic',
    'Chad', 'Comoros', 'Congo', "C\xf4te d'Ivoire", 'Democratic Republic of the Congo', 'Djibouti', 'Egypt', 
    'Equatorial Guinea', 'Eritrea', 'Ethiopia', 'Gabon', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Kenya', 
    'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 
    'Namibia', 'Niger', 'Nigeria', 'Cameroon', 'R\xe9union', 'Rwanda', 'Sao Tome and Principe', 'Senegal', 
    'Seychelles', 'Sierra Leone', 'Somalia', 'South Africa', 'Sudan', 'Swaziland', 'Togo', 'Tunisia', 
    'Uganda', 'Tanzania', 'Zambia', 'Zimbabwe']

Regions['Asia'] = ['Afghanistan', 'Armenia', 'Azerbaijan', 'Bangladesh', 'Bhutan', 'Brunei Darussalam', 'Cambodia', 'China', 
    'North Korea', 'Georgia', 'Hong Kong', 'India', 'Indonesia', 'Japan', 'Kazakhstan', 'Kyrgyzstan', 'Laos', 
    'Macao', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar', 'Nepal', 'Pakistan', 'Papua New Guinea', 
    'Philippines', 'South Korea', 'Singapore', 'Sri Lanka', 'Taiwan', 'Tajikistan', 'Thailand', 'Timor-Leste', 
    'Turkmenistan', 'Uzbekistan', 'Viet Nam']

Regions['Central America'] = ['Anguilla', 'Antigua and Barbuda', 'Aruba', 'Bahamas', 'Barbados', 'Belize', 'Bermuda', 'British Virgin Islands', 
    'Cayman Islands', 'Costa Rica', 'Cuba', 'Dominica', 'Dominican Republic', 'El Salvador', 'Grenada', 'Guadeloupe',
    'Guatemala', 'Haiti', 'Honduras', 'Jamaica', 'Martinique', 'Montserrat', 'Netherlands Antilles', 'Nicaragua', 
    'Panama', 'Saint Helena', 'Saint Lucia', 'Saint Kitts and Nevis', 'Saint Vincent and the Grenadines', 
    'Trinidad and Tobago', 'Turks and Caicos Islands']

Regions['Europe'] = ['Albania', 'Andorra', 'Austria', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 
    'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia', 'Faeroe Islands', 
    'Finland', 'France', 'Germany', 'Gibraltar', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy', 'Latvia', 
    'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macedonia (Republic of)', 'Malta', 'Montenegro', 'Netherlands', 
    'Norway', 'Poland', 'Portugal', 'Moldova', 'Romania', 'Russian Federation', 'Serbia', 'Slovakia', 
    'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Ukraine', 'United Kingdom']

Regions['Middle East'] = ['Bahrain', 'Iraq', 'Iran', 'Israel', 'Jordan', 'Kuwait', 'Lebanon', 'Occupied Palestinian Territory',
    'Oman', 'Qatar', 'Saudi Arabia', 'Syria', 'Turkey', 'United Arab Emirates', 'Yemen']

Regions['North America'] = ['Canada', 'Greenland', 'Mexico', 'Saint Pierre and Miquelon', 'United States of America']

Regions['Oceania'] = ['Australia', 'Cook Islands', 'Micronesia (Federated States of)', 'Fiji', 'French Polynesia', 
    'Kiribati', 'Marshall Islands', 'Nauru', 'New Caledonia', 'New Zealand', 'Niue', 'Palau', 
    'Samoa', 'Solomon Islands', 'Tonga', 'Vanuatu', 'Wallis and Futuna Islands']

Regions['South America'] = ['Argentina', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Falkland Islands (Malvinas)', 
    'French Guiana', 'Guyana', 'Paraguay', 'Peru', 'Bolivia', 'Suriname', 'Uruguay', 'Venezuela']

World = Regions['Africa'] + \
        Regions['Asia'] + \
        Regions['Central America'] + \
        Regions['Europe'] + \
        Regions['Middle East'] + \
        Regions['North America'] + \
        Regions['Oceania'] + \
        Regions['South America']
        
Others = ['KP Annex B', 'Non KP Annex B', 'OECD', 'Non-OECD', 'EU28', 'Statistical Difference', 'World']

In [122]:
# Create dataframe for Sources: dfS

year = 2014
# Read all csv files and create a dataframe from selected year and selected fields
dfS = pd.DataFrame()
for key in Sources.keys():
    df_full = pd.read_csv('files_csv/' + Sources[key], delimiter=';', index_col=0)
    df_select = df_full.loc[year][:]
    df_select['Source'] = key
    dfS = dfS.append(df_select)
dfS.set_index('Source', inplace=True)

# Drop already integrated regions 'Africa', 'Asia', ... and others unwanted ('OECD', 'EU28', ...)
dfS = dfS.drop(Regions.keys() + Others, axis=1)
dfS

,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,Aruba,...,United States of America,Uruguay,Uzbekistan,Vanuatu,Venezuela,Viet Nam,Wallis and Futuna Islands,Yemen,Zambia,Zimbabwe
Source,,,,,,,,,,,,,,,,,,,,,
Coal,4.671400,0.204170,0.60207,0.00000,0.00000,0.00000,0.00000,6.1735,0.012963,0.0000,...,1730.6229,0.00000,10.2022,0.00000,0.77775,86.9441,0.000000,0.0000,0.33106,9.26520
Oil,8.242500,3.612400,53.38390,0.47225,15.64130,0.14236,0.51104,94.8363,0.905740,2.4274,...,2280.2022,7.09240,8.9648,0.15477,124.64300,57.6405,0.027779,19.4361,2.37290,2.18910
Gas,0.309270,0.025914,76.41210,0.00000,1.31730,0.00000,0.00000,95.5671,3.320300,0.0000,...,1451.8760,0.19969,98.1485,0.00000,59.58600,19.6003,0.000000,1.9681,0.00000,0.00000
Gas flaring,0.000000,0.000000,6.93230,0.00000,13.81690,0.00000,0.00000,0.0000,0.000000,0.0000,...,13.0968,0.00000,0.0000,0.00000,17.85830,0.0000,0.000000,0.0000,0.00000,0.00000
Cement,0.017838,0.720590,9.96610,0.00000,0.79729,0.00000,0.00000,5.3415,0.258600,0.0000,...,38.9645,0.49830,3.5412,0.00000,3.80650,30.2685,0.000000,3.1439,0.69616,0.44701

In [123]:
# Create dataframe for Dividers: dfD

year = 2014
# Read all csv files and create a dataframe from selected year and selected fields
dfD = pd.DataFrame()
for key in Dividers.keys():
    df_full = pd.read_csv('files_csv/' + Dividers[key], delimiter=';', index_col=0)
    df_select = df_full.loc[year][:]
    df_select['Divider'] = key
    dfD = dfD.append(df_select)
dfD.set_index('Divider', inplace=True)

# Drop already integrated regions 'Africa', 'Asia', ... and others unwanted ('OECD', 'EU28', ...)
dfD = dfD.drop(Regions.keys()+Others, axis=1, errors='ignore')
dfD

,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,Aruba,...,United States of America,Uruguay,Uzbekistan,Vanuatu,Venezuela,Viet Nam,Wallis and Futuna Islands,Yemen,Zambia,Zimbabwe
Divider,,,,,,,,,,,,,,,,,,,,,
GDP,NaN,26526.6581,467732.5655,0,152590.2711,0,NaN,680732.8474,20663.1635,0,...,1.479417e+07,59144.9909,145773.8878,NaN,458310.3402,434315.6124,0,88901.6587,42279.3359,4250.626
Population,31627506,2889676.0000,38934334.0000,72786,24227524.0000,14460,90900,42980026.0000,3006154.0000,103441,...,3.194486e+08,3419516.0000,29469913.0000,258883,30693827.0000,92423338.0000,13204,26183676.0000,15721343.0000,15245855.000

In [124]:
# Create a statistical dataframe: df_stats

# Sum all sources
df_stats = pd.concat([dfS.sum()], axis=1)
df_stats.rename(columns={0: 'MtCO2'}, inplace=True)

# Concatenate dividers
df_stats = pd.concat([df_stats, dfD.loc['Population']], axis=1)
df_stats = pd.concat([df_stats, dfD.loc['GDP']], axis=1)

# When GDP == 0 set to undefined
df_stats[df_stats['GDP'] == 0 ] = np.nan

df_stats.head()

                  MtCO2  Population          GDP
Afghanistan   13.241008    31627506          NaN
Albania        4.563074     2889676   26526.6581
Algeria      147.296470    38934334  467732.5655
Andorra             NaN         NaN          NaN
Angola        31.572790    24227524  152590.2711

In [125]:
# Define a function to retrieve key from value in a dictionnary 
def keys_of_value(dict, value):
    for k in dict:
        if isinstance(dict[k], list):
            if value in dict[k]:
                return k
        else:
            if value == dict[k]:
                return k
            
print keys_of_value(Regions, 'France')

Europe

In [126]:
# Add region to df_stats
for index, row in df_stats.iterrows(): 
    df_stats.loc[index,'Region'] = keys_of_value(Regions, index)
    
df_stats = df_stats[['Region','Population','GDP','MtCO2']]
df_stats.head()

             Region  Population          GDP       MtCO2
Afghanistan    Asia    31627506          NaN   13.241008
Albania      Europe     2889676   26526.6581    4.563074
Algeria      Africa    38934334  467732.5655  147.296470
Andorra      Europe         NaN          NaN         NaN
Angola       Africa    24227524  152590.2711   31.572790

In [127]:
# Add measures 'emissions per GDP', 'emissions per capita'
df_stats['kgCO2/GDP'] = 1E3 * df_stats['MtCO2'] / df_stats['GDP']
df_stats['tCO2/person'] = 1E6 * df_stats['MtCO2'] / df_stats['Population']

# Display first 50
df_stats.sort_values(by='MtCO2', ascending=False).head(50)

,Region,Population,GDP,MtCO2,kgCO2/GDP,tCO2/person
China,Asia,1369435670,14984661.0742,9679.820800,0.645982,7.068474
United States of America,North America,319448634,14794170.9227,5514.762400,0.372766,17.263378
India,Asia,1295291543,6384811.1896,2596.712400,0.406702,2.004732
Russian Federation,Europe,143429435,2219999.2592,1572.228600,0.708211,10.961687
Japan,Asia,126794564,4053136.9433,1218.168228,0.300549,9.607417
Germany,Europe,80646262,2908146.4405,782.724740,0.269149,9.705654
Indonesia,Asia,254454778,2160960.6819,640.551600,0.296420,2.517349
Iran,Middle East,78143644,1078020.8473,615.735200,0.571172,7.879530
Saudi Arabia,Middle East,30886545,1360519.6709,601.941600,0.442435,19.488797
South Korea,Asia,50074401,1487857.1390,599.421400,0.402876,11.970615
Canada,North America,35587793,1349136.4279,545.379900,0.404244,15.324915
Brazil,South America,206077898,2605626.8115,507.290000,0.194690,2.461642
South Africa,Africa,53969054,579715.1999,476.142500,0.821339,8.822510
Mexico,North America,125385833,1627100.5855,456.635900,0.280644,3.641846
United Kingdom,Europe,64331348,2166275.2364,425.284600,0.196321,6.610845
Australia,Oceania,23622353,914769.0936,373.601800,0.408411,15.815605
Turkey,Middle East,77523788,1088809.4237,368.339590,0.338296,4.751311
Thailand,Asia,67725979,838726.3702,337.257700,0.402107,4.979739
France,Europe,64121249,1975409.4472,324.530520,0.164285,5.061201
Italy,Europe,59788667,1571082.6696,321.912010,0.204898,5.384164
Poland,Europe,38619974,742546.1727,302.511500,0.407398,7.833032
Taiwan,Asia,23361753,848878.7588,259.482600,0.305677,11.107155
Malaysia,Asia,29901997,633455.4800,251.565500,0.397132,8.413000
Egypt,Africa,89579670,801954.3853,237.446100,0.296084,2.650670
Spain,Europe,46259716,1221700.0250,235.661760,0.192897,5.094319
Ukraine,Europe,45002497,315425.7001,231.239190,0.733102,5.138364
Venezuela,South America,30693827,458310.3402,206.671550,0.450942,6.733326
Kazakhstan,Asia,17371621,355878.4629,205.246900,0.576733,11.815069
Argentina,South America,42980026,680732.8474,201.918400,0.296619,4.697959
United Arab Emirates,Middle East,9086139,510644.2176,198.206100,0.388149,21.814117
Viet Nam,Asia,92423338,434315.6124,194.453400,0.447724,2.103943
Pakistan,Asia,185044286,750856.5413,167.677300,0.223315,0.906147
Netherlands,Europe,16868020,614127.4474,152.265930,0.247939,9.026900
Algeria,Africa,38934334,467732.5655,147.296470,0.314916,3.783203
Iraq,Middle East,35273293,440078.0838,137.029900,0.311376,3.884806
Uzbekistan,Asia,29469913,145773.8878,120.856700,0.829070,4.101020
Czech Republic,Europe,10542666,254014.7926,103.159090,0.406114,9.784915
Kuwait,Middle East,3753121,246261.8250,101.834000,0.413519,27.133151
Qatar,Middle East,2172065,268825.0328,99.692300,0.370845,45.897475
Philippines,Asia,99138690,588136.0179,98.892700,0.168146,0.997519
Belgium,Europe,11226322,368588.9159,97.577020,0.264731,8.691807
Nigeria,Africa,177475986,917252.2850,93.555080,0.101995,0.527142
Chile,South America,17762647,293936.3608,81.525924,0.277359,4.589740
Colombia,South America,47791393,545258.6170,81.230400,0.148976,1.699687
Greece,Europe,11000777,227102.8117,75.676976,0.333228,6.879239
Turkmenistan,Asia,5307188,69845.1740,71.250890,1.020126,13.425356
Romania,Europe,19651554,254912.6893,70.650910,0.277157,3.595182
Oman,Middle East,4236057,141674.8773,69.759500,0.492391,16.468027
Israel,Middle East,7939483,242926.2019,67.187600,0.276576,8.462465
Bangladesh,Asia,159077513,367390.3529,66.773400,0.181751,0.419754

In [130]:
region = 'North America'
test = df_stats_selected.index[df_stats_selected['Region'] == region]
dfS.loc['Coal', test]

United States of America    1730.6229
Canada                        88.1792
Name: Coal, dtype: float64

In [42]:
dfS.loc['Oil', test]

United States of America    2280.2022
Canada                       235.7484
Name: Oil, dtype: float64

In [37]:
dfD.loc['Population', test]

United States of America    319448634
Canada                       35587793
Name: Population, dtype: float64

In [107]:
RHS = 1E6  * 1/2 * (1730.6229 + 2280.2)/319448634
RHS

6.2777274233077485

In [108]:
RHS = 1E6  * 1/2 * (88.2 + 235.7)/35587793
RHS

4.550717713795851

In [119]:
10.8/2

5.4

In [100]:
num_sources = len(Sources)
num_sources

2

In [140]:
# Create the json files for the 3 measures to be used with our Sankey visualisation

num_sources = len(Sources)

Measures = {'MtCO2': 'MtCO2', 'kgCO2/GDP': 'kgCO2_GDP', 'tCO2/person': 'tCO2_person'}

for measure in Measures.keys():
    #=============================
    # Selection
    df_stats_selected = df_stats.sort_values(by=measure, ascending=False).head(50)

    # Write the json
    print 
    file = open('emissions_' + Measures[measure] + '_v2.json', 'w')

    # nodes
    file.write('{\n')
    file.write('"nodes": [\n')
    for node in Sources.keys() + df_stats_selected['Region'].unique().tolist() + df_stats_selected.index.tolist():
        file.write('{"name": "%s"},\n' %(node))
    # remove last comma
    file.seek(-2, os.SEEK_END)
    file.truncate()
    file.write('\n],\n')

    # links
    file.write('"links": [\n')
    # Source --> Region (considering countries from the selection)
    for region in df_stats_selected['Region'].unique():        
        countries_region = df_stats_selected.index[df_stats_selected['Region'] == region]
        num_countries = len(countries_region)
        for source in Sources.keys():
            print source
            if (measure == 'MtCO2'):
                value = dfS.loc[source, countries_region].sum()
            elif (measure == 'kgCO2/GDP'):
                value = 1E3/num_countries * (dfS.loc[source, countries_region]/dfD.loc['GDP', countries_region]).sum()
            elif (measure == 'tCO2/person'):
                print "**"
                print 1E6 * dfS.loc[source, countries_region]/dfD.loc['Population', countries_region]
                value = 1E6/num_countries * (dfS.loc[source, countries_region]/dfD.loc['Population', countries_region]).sum()
                print "value: " + repr(value)
            file.write('{"source": "%s", "target": "%s", "value": "%.2f"},\n' %(source, region, value))
    # Region --> Country
    for country in df_stats_selected.index:
        region = df_stats_selected.loc[country, 'Region']
        value = df_stats_selected.loc[country, measure]      
        file.write('{"source": "%s", "target": "%s", "value": "%.2f"},\n' %(region, country, value))
    # remove last comma
    file.seek(-2, os.SEEK_END)
    file.truncate()
    file.write('\n]\n')
    file.write('}\n')

    file.close()

Coal
Oil
Gas
Gas flaring
Cement
Coal
Oil
Gas
Gas flaring
Cement
Coal
Oil
Gas
Gas flaring
Cement
Coal
Oil
Gas
Gas flaring
Cement
Coal
Oil
Gas
Gas flaring
Cement
Coal
Oil
Gas
Gas flaring
Cement
Coal
Oil
Gas
Gas flaring
Cement

Coal
Oil
Gas
Gas flaring
Cement
Coal
Oil
Gas
Gas flaring
Cement
Coal
Oil
Gas
Gas flaring
Cement
Coal
Oil
Gas
Gas flaring
Cement
Coal
Oil
Gas
Gas flaring
Cement
Coal
Oil
Gas
Gas flaring
Cement
Coal
Oil
Gas
Gas flaring
Cement
Coal
Oil
Gas
Gas flaring
Cement

Coal
**
Qatar                        NaN
Kuwait                       NaN
United Arab Emirates    0.716652
Saudi Arabia            0.000000
Bahrain                 0.000000
Oman                    0.000000
Israel                  3.207564
Iran                    0.052029
dtype: float64
value: 0.49703057464972805
Oil
**
Qatar                    8.617652
Kuwait                  16.381380
United Arab Emirates     5.555495
Saudi Arabia            12.382541
Bahrain                  3.538875
Oman                     4.486507
Israel                   3.122936
Iran                     3.024548
dtype: float64
value: 7.1387417085230984
Gas
**
Qatar                   35.776139
Kuwait                  10.341740
United Arab Emirates    14.453378
Saudi Arabia             6.089807
Bahrain                 14.858473
Oman                    11.014087
Israel                   1.804500
Iran                     3.933356
dtype: float64
value: 12.283935042388997
Gas flaring
**
Qatar                   0.494276
Kuwait                  0.111294
United Arab Emirates    0.208075
Saudi Arabia            0.000000
Bahrain                 0.000000
Oman                    0.416897
Israel                  0.000000
Iran                    0.427572
dtype: float64
value: 0.20726426190487726
Cement
**
Qatar                   1.009408
Kuwait                  0.298738
United Arab Emirates    0.880517
Saudi Arabia            1.016449
Bahrain                 0.317682
Oman                    0.550536
Israel                  0.327465
Iran                    0.442026
dtype: float64
value: 0.60535245826194062
Coal
**
Trinidad and Tobago   NaN
dtype: float64
value: nan
Oil
**
Trinidad and Tobago    3.389707
dtype: float64
value: 3.3897066260706117
Gas
**
Trinidad and Tobago    30.845939
dtype: float64
value: 30.845939004033269
Gas flaring
**
Trinidad and Tobago    0
dtype: float64
value: 0.0
Cement
**
Trinidad and Tobago    0.233174
dtype: float64
value: 0.2331738382836846
Coal
**
Brunei Darussalam    0.000000
Turkmenistan              NaN
South Korea          6.168120
Kazakhstan           7.774093
Taiwan               6.188530
Japan                3.462040
Malaysia             2.220751
Mongolia             5.926483
China                4.994590
dtype: float64
value: 4.0816230233906321
Oil
**
Brunei Darussalam    4.772948
Turkmenistan         3.598422
South Korea          3.365540
Kazakhstan           2.134752
Taiwan               2.967256
Japan                3.837091
Malaysia             2.743680
Mongolia             1.129225
China                0.923618
dtype: float64
value: 2.8302813281339927
Gas
**
Brunei Darussalam    17.544814
Turkmenistan          9.684394
South Korea           1.961765
Kazakhstan            1.641856
Taiwan                1.614211
Japan                 2.098618
Malaysia              2.553452
Mongolia              0.000000
China                 0.240577
dtype: float64
value: 4.1488540930076949
Gas flaring
**
Brunei Darussalam    1.176299
Turkmenistan         0.000000
South Korea          0.000000
Kazakhstan           0.138508
Taiwan               0.000000
Japan                0.000246
Malaysia             0.562063
Mongolia             0.000000
China                0.000000
dtype: float64
value: 0.20856836085157004
Cement
**
Brunei Darussalam    0.281509
Turkmenistan         0.142541
South Korea          0.475191
Kazakhstan           0.125860
Taiwan               0.337158
Japan                0.209421
Malaysia             0.333055
Mongolia             0.042294
China                0.909689
dtype: float64
value: 0.3174129336221137
Coal
**
Luxembourg            0.490070
Estonia               8.843545
Russian Federation    2.499235
Czech Republic        6.053820
Germany               4.295609
Iceland               4.817945
Netherlands           2.062732
Belgium               1.499307
Finland               2.317334
Norway                0.986447
Poland                5.275353
Ireland               1.708111
Austria               1.392382
Slovenia              2.780209
Greece                3.130824
Denmark               1.820504
Malta                 0.000020
United Kingdom        1.733174
Cyprus                0.000987
Bulgaria              3.807281
Belarus               0.383699
Slovakia              2.547585
dtype: float64
value: 2.6566441442124153
Oil
**
Luxembourg            13.487898
Estonia                2.400921
Russian Federation     2.276479
Czech Republic         2.203437
Germany                3.166103
Iceland                4.586671
Netherlands            2.895491
Belgium                4.105138
Finland                4.581525
Norway                 4.256610
Poland                 1.558567
Ireland                3.753879
Austria                3.818237
Slovenia               3.576939
Greece                 2.966872
Denmark                3.446529
Malta                  6.751364
United Kingdom         2.555378
Cyprus                 5.682533
Bulgaria               1.427505
Belarus                1.453472
Slovakia               1.458916
dtype: float64
value: 3.7459302143769442
Gas
**
Luxembourg            4.276528
Estonia               0.863469
Russian Federation    5.726152
Czech Republic        1.382629
Germany               2.084487
Iceland               0.019330
Netherlands           4.046907
Belgium               2.843772
Finland               1.501462
Norway                2.695703
Poland                0.833802
Ireland               1.921622
Austria               1.842533
Slovenia              0.711835
Greece                0.499056
Denmark               1.303317
Malta                 0.000673
United Kingdom        2.213905
Cyprus                0.003806
Bulgaria              0.740227
Belarus               3.998222
Slovakia              1.472839
dtype: float64
value: 1.8628306888915687
Gas flaring
**
Luxembourg            0.000000e+00
Estonia               0.000000e+00
Russian Federation    2.551380e-01
Czech Republic        1.137283e-03
Germany               5.042267e-03
Iceland               0.000000e+00
Netherlands           3.506043e-03
Belgium               8.196807e-03
Finland               1.833690e-02
Norway                2.641235e-01
Poland                0.000000e+00
Ireland               0.000000e+00
Austria               0.000000e+00
Slovenia              0.000000e+00
Greece                7.523287e-04
Denmark               3.841223e-02
Malta                 0.000000e+00
United Kingdom        5.063317e-02
Cyprus                0.000000e+00
Bulgaria              3.208723e-04
Belarus               2.116643e-04
Slovakia              2.319440e-07
dtype: float64
value: 0.029355060814902332
Cement
**
Luxembourg            0.673515
Estonia               0.309557
Russian Federation    0.204683
Czech Republic        0.143891
Germany               0.154413
Iceland               0.000000
Netherlands           0.018265
Belgium               0.235393
Finland               0.091177
Norway                0.140914
Poland                0.165311
Ireland               0.251756
Austria               0.196374
Slovenia              0.157744
Greece                0.281735
Denmark               0.154258
Malta                 0.000000
United Kingdom        0.057756
Cyprus                0.437339
Bulgaria              0.138562
Belarus               0.229832
Slovakia              0.198899
dtype: float64
value: 0.19278969412736141
Coal
**
United States of America    5.417531
Canada                      2.477793
dtype: float64
value: 3.9476622545016
Oil
**
United States of America    7.137931
Canada                      6.624418
dtype: float64
value: 6.881174099449427
Gas
**
United States of America    4.544944
Canada                      5.915003
dtype: float64
value: 5.2299732283191673
Gas flaring
**
United States of America    0.040998
Canada                      0.131045
dtype: float64
value: 0.086021537494736816
Cement
**
United States of America    0.121974
Canada                      0.176656
dtype: float64
value: 0.14931515308793394
Coal
**
Australia      7.501323
Palau          0.000000
New Zealand    1.351913
dtype: float64
value: 2.9510786271528677
Oil
**
Australia       5.145292
Palau          11.474617
New Zealand     4.036408
dtype: float64
value: 6.8854390626153856
Gas
**
Australia      2.892595
Palau          0.000000
New Zealand    1.914544
dtype: float64
value: 1.6023798057908978
Gas flaring
**
Australia      0.127460
Palau          0.000000
New Zealand    0.052462
dtype: float64
value: 0.059973781277269107
Cement
**
Australia      0.148935
Palau          0.000000
New Zealand    0.126489
dtype: float64
value: 0.091808140987388612
Coal
**
South Africa         7.326845
Equatorial Guinea    0.000000
Seychelles           0.000000
Libya                0.000000
dtype: float64
value: 1.8317112803200146
Oil
**
South Africa         1.221506
Equatorial Guinea    0.732855
Seychelles           7.103100
Libya                4.521453
dtype: float64
value: 3.3947284354056424
Gas
**
South Africa         0.167411
Equatorial Guinea    4.420351
Seychelles           0.000000
Libya                1.524896
dtype: float64
value: 1.5281645033285989
Gas flaring
**
South Africa         0.000000
Equatorial Guinea    2.789672
Seychelles           0.000000
Libya                0.400416
dtype: float64
value: 0.79752213689357299
Cement
**
South Africa         0.106748
Equatorial Guinea    0.000000
Seychelles           0.000000
Libya                0.136482
dtype: float64
value: 0.06080760666861551
Coal
**
Venezuela    0.025339
dtype: float64
value: 0.025338971253079649
Oil
**
Venezuela    4.060849
dtype: float64
value: 4.0608491081936435
Gas
**
Venezuela    1.941302
dtype: float64
value: 1.9413023993391247
Gas flaring
**
Venezuela    0.581821
dtype: float64
value: 0.5818205725861425
Cement
**
Venezuela    0.124015
dtype: float64
value: 0.12401516435210247

In [93]:
7.895324509 + 13.7623481989

21.657672707899998

In [139]:
(3.95+.5+4.08+2.66+2.95+1.83+.025)/7

2.285