Patrick BROCKMANN<br>
Software engineer at LSCE (Climate and Environment Sciences Laboratory)<br>
<img align="left" width="40%" src="http://www.lsce.ipsl.fr/Css/img/banniere_LSCE_75.png"><br><br>
<hr>

Coded 01/02/2016

In [1]:
import numpy as np
import pandas as pd
import collections
import os

In [2]:
# Define CSV files for sources and dividers
Sources = collections.OrderedDict()
Sources['Coal'] = 'coal.csv'
Sources['Oil']='oil.csv'   
Sources['Gas']='gas.csv'
Sources['Gas flaring']='flaring.csv'
Sources['Cement']='cement.csv'

Dividers = collections.OrderedDict()
Dividers['GDP']='gdp.csv'
Dividers['Population']='population.csv'

In [3]:
# Units
# kgCO2/GDP = 1E3 * 'MtCO2' / 'GDP'
# tCO2/person = 1E6 * 'MtCO2' / 'Population'

In [4]:
# Create dataframe for Sources: dfS

year = 2014
# Read all csv files and create a dataframe from selected year and selected fields
dfS = pd.DataFrame()
for key in Sources.keys():
    df_full = pd.read_csv('files_csv/' + Sources[key], delimiter=';', index_col=0)
    df_select = df_full.loc[year][:]
    df_select['Source'] = key
    dfS = dfS.append(df_select)
dfS.set_index('Source', inplace=True)

dfS

,Afghanistan,Africa,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,...,Uruguay,Uzbekistan,Vanuatu,Venezuela,Viet Nam,Wallis and Futuna Islands,World,Yemen,Zambia,Zimbabwe
Source,,,,,,,,,,,,,,,,,,,,,
Coal,4.671400,443.7634,0.204170,0.60207,0.00000,0.00000,0.00000,0.00000,6.1735,0.012963,...,0.00000,10.2022,0.00000,0.77775,86.9441,0.000000,15050.0463,0.0000,0.33106,9.26520
Oil,8.242500,489.8935,3.612400,53.38390,0.47225,15.64130,0.14236,0.51104,94.8363,0.905740,...,7.09240,8.9648,0.15477,124.64300,57.6405,0.027779,11847.7270,19.4361,2.37290,2.18910
Gas,0.309270,229.5443,0.025914,76.41210,0.00000,1.31730,0.00000,0.00000,95.5671,3.320300,...,0.19969,98.1485,0.00000,59.58600,19.6003,0.000000,6700.7971,1.9681,0.00000,0.00000
Gas flaring,0.000000,53.3991,0.000000,6.93230,0.00000,13.81690,0.00000,0.00000,0.0000,0.000000,...,0.00000,0.0000,0.00000,17.85830,0.0000,0.000000,230.8320,0.0000,0.00000,0.00000
Cement,0.017838,78.0755,0.720590,9.96610,0.00000,0.79729,0.00000,0.00000,5.3415,0.258600,...,0.49830,3.5412,0.00000,3.80650,30.2685,0.000000,2060.2521,3.1439,0.69616,0.44701

In [5]:
# Create dataframe for Dividers: dfD

year = 2014
# Read all csv files and create a dataframe from selected year and selected fields
dfD = pd.DataFrame()
for key in Dividers.keys():
    df_full = pd.read_csv('files_csv/' + Dividers[key], delimiter=';', index_col=0)
    df_select = df_full.loc[year][:]
    df_select['Divider'] = key
    dfD = dfD.append(df_select)
dfD.set_index('Divider', inplace=True)

dfD

,Afghanistan,Africa,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,...,Uruguay,Uzbekistan,Vanuatu,Venezuela,Viet Nam,Wallis and Futuna Islands,World,Yemen,Zambia,Zimbabwe
Divider,,,,,,,,,,,,,,,,,,,,,
GDP,NaN,4.187801e+06,26526.6581,467732.5655,0,152590.2711,0,NaN,680732.8474,20663.1635,...,59144.9909,145773.8878,NaN,458310.3402,434315.6124,0,8.857878e+07,88901.6587,42279.3359,4250.626
Population,31627506,1.155850e+09,2889676.0000,38934334.0000,72786,24227524.0000,14460,90900,42980026.0000,3006154.0000,...,3419516.0000,29469913.0000,258883,30693827.0000,92423338.0000,13204,7.265786e+09,26183676.0000,15721343.0000,15245855.000

In [15]:
dfD['China']['Population']

1369435670.0

In [6]:
#Drop "Source" header name from index column before transposing
dfS.index.name = ""
dfS

,Afghanistan,Africa,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,...,Uruguay,Uzbekistan,Vanuatu,Venezuela,Viet Nam,Wallis and Futuna Islands,World,Yemen,Zambia,Zimbabwe
,,,,,,,,,,,,,,,,,,,,,
Coal,4.671400,443.7634,0.204170,0.60207,0.00000,0.00000,0.00000,0.00000,6.1735,0.012963,...,0.00000,10.2022,0.00000,0.77775,86.9441,0.000000,15050.0463,0.0000,0.33106,9.26520
Oil,8.242500,489.8935,3.612400,53.38390,0.47225,15.64130,0.14236,0.51104,94.8363,0.905740,...,7.09240,8.9648,0.15477,124.64300,57.6405,0.027779,11847.7270,19.4361,2.37290,2.18910
Gas,0.309270,229.5443,0.025914,76.41210,0.00000,1.31730,0.00000,0.00000,95.5671,3.320300,...,0.19969,98.1485,0.00000,59.58600,19.6003,0.000000,6700.7971,1.9681,0.00000,0.00000
Gas flaring,0.000000,53.3991,0.000000,6.93230,0.00000,13.81690,0.00000,0.00000,0.0000,0.000000,...,0.00000,0.0000,0.00000,17.85830,0.0000,0.000000,230.8320,0.0000,0.00000,0.00000
Cement,0.017838,78.0755,0.720590,9.96610,0.00000,0.79729,0.00000,0.00000,5.3415,0.258600,...,0.49830,3.5412,0.00000,3.80650,30.2685,0.000000,2060.2521,3.1439,0.69616,0.44701

In [7]:
#Create a df with columns for each country and source emission by transposing df_stats
df_statsT = pd.DataFrame(dfS.T)
#df_statsT.rename(columns = {'Source':'Country'})
print df_statsT.index.name

df_statsT.head(15)

None

,Coal,Oil,Gas,Gas flaring,Cement
Afghanistan,4.671400,8.24250,0.309270,0.0000,0.017838
Africa,443.763400,489.89350,229.544300,53.3991,78.075500
Albania,0.204170,3.61240,0.025914,0.0000,0.720590
Algeria,0.602070,53.38390,76.412100,6.9323,9.966100
Andorra,0.000000,0.47225,0.000000,0.0000,0.000000
Angola,0.000000,15.64130,1.317300,13.8169,0.797290
Anguilla,0.000000,0.14236,0.000000,0.0000,0.000000
Antigua and Barbuda,0.000000,0.51104,0.000000,0.0000,0.000000
Argentina,6.173500,94.83630,95.567100,0.0000,5.341500
Armenia,0.012963,0.90574,3.320300,0.0000,0.258600
Aruba,0.000000,2.42740,0.000000,0.0000,0.000000
Asia,10551.210100,3230.10270,1426.682100,34.5633,1561.763100
Australia,177.198900,121.54390,68.329900,3.0109,3.518200
Austria,11.858800,32.51960,15.692700,0.0000,1.672500
Azerbaijan,0.021151,11.94620,21.528300,3.2023,0.995840

In [18]:
#Sum contributions from all sources

source_list= list(df_statsT)
print source_list

df_statsT['MtCO2'] = df_statsT[source_list].sum(axis=1)
df_statsT.head(15)

['Coal', 'Oil', 'Gas', 'Gas flaring', 'Cement']

,Coal,Oil,Gas,Gas flaring,Cement,MtCO2
Afghanistan,4.671400,8.24250,0.309270,0.0000,0.017838,13.241008
Africa,443.763400,489.89350,229.544300,53.3991,78.075500,1294.675800
Albania,0.204170,3.61240,0.025914,0.0000,0.720590,4.563074
Algeria,0.602070,53.38390,76.412100,6.9323,9.966100,147.296470
Andorra,0.000000,0.47225,0.000000,0.0000,0.000000,0.472250
Angola,0.000000,15.64130,1.317300,13.8169,0.797290,31.572790
Anguilla,0.000000,0.14236,0.000000,0.0000,0.000000,0.142360
Antigua and Barbuda,0.000000,0.51104,0.000000,0.0000,0.000000,0.511040
Argentina,6.173500,94.83630,95.567100,0.0000,5.341500,201.918400
Armenia,0.012963,0.90574,3.320300,0.0000,0.258600,4.497603
Aruba,0.000000,2.42740,0.000000,0.0000,0.000000,2.427400
Asia,10551.210100,3230.10270,1426.682100,34.5633,1561.763100,16804.321300
Australia,177.198900,121.54390,68.329900,3.0109,3.518200,373.601800
Austria,11.858800,32.51960,15.692700,0.0000,1.672500,61.743600
Azerbaijan,0.021151,11.94620,21.528300,3.2023,0.995840,37.693791

In [19]:
#Add MtCO2, GDP and Population dividers to df_statsT
#(use MtCO2 col to sort top 50 emitter countries)

df_statsT = pd.concat([df_statsT, dfD.loc['Population']], axis=1)
df_statsT = pd.concat([df_statsT, dfD.loc['GDP']], axis=1)

# When GDP == 0 set to undefined
df_statsT[df_statsT['GDP'] == 0 ] = np.nan

#normalize MtCO2 by GDP and Population to use in ranking later on
df_statsT['MtCO2perGDP'] = (1E3 * df_statsT['MtCO2']) / df_statsT['GDP']
df_statsT['MtCO2perPop'] = (1E6 * df_statsT['MtCO2']) / df_statsT['Population']


df_statsT.index.name = 'Country'
df_statsT.head(10)

,Coal,Oil,Gas,Gas flaring,Cement,MtCO2,Population,GDP,MtCO2perGDP,MtCO2perPop
Country,,,,,,,,,,
Afghanistan,4.671400,8.24250,0.309270,0.0000,0.017838,13.241008,31627506,NaN,NaN,0.418655
Africa,443.763400,489.89350,229.544300,53.3991,78.075500,1294.675800,1155850095,4187800.9385,0.309154,1.120107
Albania,0.204170,3.61240,0.025914,0.0000,0.720590,4.563074,2889676,26526.6581,0.172018,1.579095
Algeria,0.602070,53.38390,76.412100,6.9323,9.966100,147.296470,38934334,467732.5655,0.314916,3.783203
Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Angola,0.000000,15.64130,1.317300,13.8169,0.797290,31.572790,24227524,152590.2711,0.206912,1.303179
Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Antigua and Barbuda,0.000000,0.51104,0.000000,0.0000,0.000000,0.511040,90900,NaN,NaN,5.622002
Argentina,6.173500,94.83630,95.567100,0.0000,5.341500,201.918400,42980026,680732.8474,0.296619,4.697959
Armenia,0.012963,0.90574,3.320300,0.0000,0.258600,4.497603,3006154,20663.1635,0.217663,1.496132

In [20]:
#Keep only top 50 emitters for each measure

df_statsT_MtCO2_top50 = df_statsT.sort_values(by='MtCO2', ascending=False).head(50)
df_statsT_GDP_top50 = df_statsT.sort_values(by='MtCO2perGDP', ascending=False).head(50)
df_statsT_Pop_top50 = df_statsT.sort_values(by='MtCO2perPop', ascending=False).head(50)

In [26]:
df_statsT_GDP_top50.head(10)

,Coal,Oil,Gas,Gas flaring,Cement,MtCO2,Population,GDP,MtCO2perGDP,MtCO2perPop,CoalperGDP,OilperGDP,GasperGDP,GFperGDP,CementperGDP
Country,,,,,,,,,,,,,,,
Zimbabwe,9.2652,2.1891,0.00000,0.00000,0.44701,11.90131,15245855,4250.6260,2.799896,0.780626,2.179726,0.515006,0.000000,0.000000,0.105163
Trinidad and Tobago,NaN,4.5913,41.78030,0.00000,0.31583,46.68743,1354483,35567.2420,1.312653,34.468819,NaN,0.129088,1.174685,0.000000,0.008880
Turkmenistan,NaN,19.0975,51.39690,0.00000,0.75649,71.25089,5307188,69845.1740,1.020126,13.425356,NaN,0.273426,0.735869,0.000000,0.010831
Libya,0.0000,28.2997,9.54430,2.50620,0.85424,41.20444,6258984,44506.3970,0.925809,6.583247,0.000000,0.635857,0.214448,0.056311,0.019194
Mongolia,17.2453,3.2859,0.00000,0.00000,0.12307,20.65427,2909871,24858.5532,0.830872,7.098002,0.693737,0.132184,0.000000,0.000000,0.004951
Uzbekistan,10.2022,8.9648,98.14850,0.00000,3.54120,120.85670,29469913,145773.8878,0.829070,4.101020,0.069986,0.061498,0.673293,0.000000,0.024292
South Africa,395.4229,65.9235,9.03500,0.00000,5.76110,476.14250,53969054,579715.1999,0.821339,8.822510,0.682099,0.113717,0.015585,0.000000,0.009938
Ukraine,120.4939,30.7738,76.53290,0.22149,3.21710,231.23919,45002497,315425.7001,0.733102,5.138364,0.382004,0.097563,0.242634,0.000702,0.010199
Bosnia and Herzegovina,16.2264,4.2503,0.45998,0.00000,0.42001,21.35669,3817554,29200.4951,0.731381,5.594339,0.555689,0.145556,0.015752,0.000000,0.014384
Russian Federation,358.4639,326.5141,821.29870,36.59430,29.35760,1572.22860,143429435,2219999.2592,0.708211,10.961687,0.161470,0.147078,0.369954,0.016484,0.013224

In [22]:
#make a dataframe for each measure

#Normalized by GDP
df_statsT_GDP_top50['CoalperGDP'] = 1E3 * df_statsT_GDP_top50['Coal'] / df_statsT_GDP_top50['GDP']
df_statsT_GDP_top50['OilperGDP'] = 1E3 * df_statsT_GDP_top50['Oil'] / df_statsT_GDP_top50['GDP']
df_statsT_GDP_top50['GasperGDP'] = 1E3 * df_statsT_GDP_top50['Gas'] / df_statsT_GDP_top50['GDP']
df_statsT_GDP_top50['GFperGDP'] = 1E3 * df_statsT_GDP_top50['Gas flaring'] / df_statsT_GDP_top50['GDP']
df_statsT_GDP_top50['CementperGDP'] = 1E3 * df_statsT_GDP_top50['Cement'] / df_statsT_GDP_top50['GDP']

In [23]:
df_statsT_GDP_top50.head(10)

,Coal,Oil,Gas,Gas flaring,Cement,MtCO2,Population,GDP,MtCO2perGDP,MtCO2perPop,CoalperGDP,OilperGDP,GasperGDP,GFperGDP,CementperGDP
Country,,,,,,,,,,,,,,,
Zimbabwe,9.2652,2.1891,0.00000,0.00000,0.44701,11.90131,15245855,4250.6260,2.799896,0.780626,2.179726,0.515006,0.000000,0.000000,0.105163
Trinidad and Tobago,NaN,4.5913,41.78030,0.00000,0.31583,46.68743,1354483,35567.2420,1.312653,34.468819,NaN,0.129088,1.174685,0.000000,0.008880
Turkmenistan,NaN,19.0975,51.39690,0.00000,0.75649,71.25089,5307188,69845.1740,1.020126,13.425356,NaN,0.273426,0.735869,0.000000,0.010831
Libya,0.0000,28.2997,9.54430,2.50620,0.85424,41.20444,6258984,44506.3970,0.925809,6.583247,0.000000,0.635857,0.214448,0.056311,0.019194
Mongolia,17.2453,3.2859,0.00000,0.00000,0.12307,20.65427,2909871,24858.5532,0.830872,7.098002,0.693737,0.132184,0.000000,0.000000,0.004951
Uzbekistan,10.2022,8.9648,98.14850,0.00000,3.54120,120.85670,29469913,145773.8878,0.829070,4.101020,0.069986,0.061498,0.673293,0.000000,0.024292
South Africa,395.4229,65.9235,9.03500,0.00000,5.76110,476.14250,53969054,579715.1999,0.821339,8.822510,0.682099,0.113717,0.015585,0.000000,0.009938
Ukraine,120.4939,30.7738,76.53290,0.22149,3.21710,231.23919,45002497,315425.7001,0.733102,5.138364,0.382004,0.097563,0.242634,0.000702,0.010199
Bosnia and Herzegovina,16.2264,4.2503,0.45998,0.00000,0.42001,21.35669,3817554,29200.4951,0.731381,5.594339,0.555689,0.145556,0.015752,0.000000,0.014384
Russian Federation,358.4639,326.5141,821.29870,36.59430,29.35760,1572.22860,143429435,2219999.2592,0.708211,10.961687,0.161470,0.147078,0.369954,0.016484,0.013224

In [24]:
#Normalized by Population
df_statsT_Pop_top50['CoalperPop'] = 1E6 * df_statsT_Pop_top50['Coal'] / df_statsT_Pop_top50['Population']
df_statsT_Pop_top50['OilperPop'] = 1E6 * df_statsT_Pop_top50['Oil'] / df_statsT_Pop_top50['Population']
df_statsT_Pop_top50['GasperPop'] = 1E6 * df_statsT_Pop_top50['Gas'] / df_statsT_Pop_top50['Population']
df_statsT_Pop_top50['GFperPop'] = 1E6 * df_statsT_Pop_top50['Gas flaring'] / df_statsT_Pop_top50['Population']
df_statsT_Pop_top50['CementperPop'] = 1E6 * df_statsT_Pop_top50['Cement'] / df_statsT_Pop_top50['Population']

In [25]:
df_statsT_Pop_top50.head(10)

,Coal,Oil,Gas,Gas flaring,Cement,MtCO2,Population,GDP,MtCO2perGDP,MtCO2perPop,CoalperPop,OilperPop,GasperPop,GFperPop,CementperPop
Country,,,,,,,,,,,,,,,
Qatar,NaN,18.7181,77.7081,1.07360,2.19250,99.69230,2172065,268825.0328,0.370845,45.897475,NaN,8.617652,35.776139,0.494276,1.009408
Trinidad and Tobago,NaN,4.5913,41.7803,0.00000,0.31583,46.68743,1354483,35567.2420,1.312653,34.468819,NaN,3.389707,30.845939,0.000000,0.233174
Kuwait,NaN,61.4813,38.8138,0.41770,1.12120,101.83400,3753121,246261.8250,0.413519,27.133151,NaN,16.381380,10.341740,0.111294,0.298738
Brunei Darussalam,0.00000,1.9922,7.3231,0.49098,0.11750,9.92378,417394,24965.7076,0.397496,23.775569,0.000000,4.772948,17.544814,1.176299,0.281509
United Arab Emirates,6.51160,50.4780,131.3254,1.89060,8.00050,198.20610,9086139,510644.2176,0.388149,21.814117,0.716652,5.555495,14.453378,0.208075,0.880517
Saudi Arabia,0.00000,382.4539,188.0931,0.00000,31.39460,601.94160,30886545,1360519.6709,0.442435,19.488797,0.000000,12.382541,6.089807,0.000000,1.016449
Luxembourg,0.27276,7.5070,2.3802,0.00000,0.37486,10.53482,556573,38521.6342,0.273478,18.928011,0.490070,13.487898,4.276528,0.000000,0.673515
Bahrain,0.00000,4.8197,20.2362,0.00000,0.43266,25.48856,1361930,52577.4765,0.484781,18.715029,0.000000,3.538875,14.858473,0.000000,0.317682
United States of America,1730.62290,2280.2022,1451.8760,13.09680,38.96450,5514.76240,319448634,14794170.9227,0.372766,17.263378,5.417531,7.137931,4.544944,0.040998,0.121974
Oman,0.00000,19.0051,46.6563,1.76600,2.33210,69.75950,4236057,141674.8773,0.492391,16.468027,0.000000,4.486507,11.014087,0.416897,0.550536

In [27]:
#DROP EXTRA COLUMNS BEFORE SAVING TO CSV

df_statsT_MtCO2_top50.drop('MtCO2', axis=1, inplace=True)
df_statsT_MtCO2_top50.drop('Population', axis=1, inplace=True)
df_statsT_MtCO2_top50.drop('GDP', axis=1, inplace=True)
df_statsT_MtCO2_top50.drop('MtCO2perGDP', axis=1, inplace=True)
df_statsT_MtCO2_top50.drop('MtCO2perPop', axis=1, inplace=True)


df_statsT_MtCO2_top50.head(10)

,Coal,Oil,Gas,Gas flaring,Cement
Country,,,,,
World,15050.04630,11847.7270,6700.7971,230.832000,2060.25210
Non-OECD,10943.59010,5302.5103,3442.0307,214.248200,1796.76220
Non KP Annex B,10945.67540,5477.6190,2868.2160,185.192700,1839.86250
Asia,10551.21010,3230.1027,1426.6821,34.563300,1561.76310
KP Annex B,4032.28010,4890.5887,3764.6739,64.955600,181.29980
OECD,4034.36540,5065.6975,3190.8592,35.900100,224.40010
China,6839.77020,1264.8356,329.4550,0.000000,1245.76000
North America,1848.51080,2774.2560,1806.5152,25.579400,62.69060
United States of America,1730.62290,2280.2022,1451.8760,13.096800,38.96450
Europe,1648.44620,1795.5794,1803.5072,43.919200,111.26520
EU28,1105.03150,1346.6709,839.7128,5.713300,70.82550
India,1934.35860,453.5116,72.8206,2.077500,133.94410
Middle East,182.77980,1086.5916,954.8333,58.432100,133.52510
Statistical Difference,72.09070,1479.5192,67.9072,-19.316200,39.08980
Russian Federation,358.46390,326.5141,821.2987,36.594300,29.35760
Africa,443.76340,489.8935,229.5443,53.399100,78.07550
Japan,438.96790,486.5223,266.0934,0.031228,26.55340
South America,111.08490,721.4600,287.7939,31.004800,62.30210
Germany,346.42480,255.3344,168.1061,0.406640,12.45280
Indonesia,321.83310,216.8419,72.5128,9.537400,19.82640
Iran,4.06570,236.3492,307.3668,33.412000,34.54150
Saudi Arabia,0.00000,382.4539,188.0931,0.000000,31.39460
South Korea,308.86490,168.5274,98.2342,0.000000,23.79490
Canada,88.17920,235.7484,210.5019,4.663600,6.28680
Brazil,63.32480,329.5170,74.9525,3.616400,35.87930
South Africa,395.42290,65.9235,9.0350,0.000000,5.76110
Mexico,29.70880,257.5316,144.1373,7.819000,17.43920
United Kingdom,111.49740,164.3909,142.4235,3.257300,3.71550
Oceania,184.90790,145.8208,76.9368,3.246700,4.20820
Australia,177.19890,121.5439,68.3299,3.010900,3.51820
Turkey,146.22620,89.5806,96.8241,0.101190,35.60750
Thailand,71.57200,157.4213,87.2931,0.000000,20.97130
France,38.03670,198.1387,80.4044,0.449220,7.50150
Italy,52.62220,138.9975,123.2604,0.317610,6.71430
Poland,203.73400,60.1918,32.2014,0.000000,6.38430
Taiwan,144.57490,69.3203,37.7108,0.000000,7.87660
Malaysia,66.40490,82.0415,76.3533,16.806800,9.95900
Egypt,5.83420,112.6224,93.7205,0.000000,25.26900
Spain,47.55900,124.5006,54.4262,0.421760,8.75420
Ukraine,120.49390,30.7738,76.5329,0.221490,3.21710
Venezuela,0.77775,124.6430,59.5860,17.858300,3.80650
Kazakhstan,135.04860,37.0841,28.5217,2.406100,2.18640
Argentina,6.17350,94.8363,95.5671,0.000000,5.34150
United Arab Emirates,6.51160,50.4780,131.3254,1.890600,8.00050
Viet Nam,86.94410,57.6405,19.6003,0.000000,30.26850
Central America,7.25240,124.5037,47.0772,0.003664,7.33260
Pakistan,18.99150,63.5971,69.1430,0.000000,15.94570
Netherlands,34.79420,48.8412,68.2633,0.059140,0.30809
Algeria,0.60207,53.3839,76.4121,6.932300,9.96610
Iraq,0.00000,101.8917,12.6633,18.488500,3.98640

In [28]:
df_statsT_GDP_top50.head(10)

,Coal,Oil,Gas,Gas flaring,Cement,MtCO2,Population,GDP,MtCO2perGDP,MtCO2perPop,CoalperGDP,OilperGDP,GasperGDP,GFperGDP,CementperGDP
Country,,,,,,,,,,,,,,,
Zimbabwe,9.2652,2.1891,0.00000,0.00000,0.44701,11.90131,15245855,4250.6260,2.799896,0.780626,2.179726,0.515006,0.000000,0.000000,0.105163
Trinidad and Tobago,NaN,4.5913,41.78030,0.00000,0.31583,46.68743,1354483,35567.2420,1.312653,34.468819,NaN,0.129088,1.174685,0.000000,0.008880
Turkmenistan,NaN,19.0975,51.39690,0.00000,0.75649,71.25089,5307188,69845.1740,1.020126,13.425356,NaN,0.273426,0.735869,0.000000,0.010831
Libya,0.0000,28.2997,9.54430,2.50620,0.85424,41.20444,6258984,44506.3970,0.925809,6.583247,0.000000,0.635857,0.214448,0.056311,0.019194
Mongolia,17.2453,3.2859,0.00000,0.00000,0.12307,20.65427,2909871,24858.5532,0.830872,7.098002,0.693737,0.132184,0.000000,0.000000,0.004951
Uzbekistan,10.2022,8.9648,98.14850,0.00000,3.54120,120.85670,29469913,145773.8878,0.829070,4.101020,0.069986,0.061498,0.673293,0.000000,0.024292
South Africa,395.4229,65.9235,9.03500,0.00000,5.76110,476.14250,53969054,579715.1999,0.821339,8.822510,0.682099,0.113717,0.015585,0.000000,0.009938
Ukraine,120.4939,30.7738,76.53290,0.22149,3.21710,231.23919,45002497,315425.7001,0.733102,5.138364,0.382004,0.097563,0.242634,0.000702,0.010199
Bosnia and Herzegovina,16.2264,4.2503,0.45998,0.00000,0.42001,21.35669,3817554,29200.4951,0.731381,5.594339,0.555689,0.145556,0.015752,0.000000,0.014384
Russian Federation,358.4639,326.5141,821.29870,36.59430,29.35760,1572.22860,143429435,2219999.2592,0.708211,10.961687,0.161470,0.147078,0.369954,0.016484,0.013224

In [29]:

df_statsT_GDP_top50.drop('Coal', axis=1, inplace=True)
df_statsT_GDP_top50.drop('Oil', axis=1, inplace=True)
df_statsT_GDP_top50.drop('Gas', axis=1, inplace=True)
df_statsT_GDP_top50.drop('Gas flaring', axis=1, inplace=True)
df_statsT_GDP_top50.drop('Cement', axis=1, inplace=True)
df_statsT_GDP_top50.drop('MtCO2', axis=1, inplace=True)
df_statsT_GDP_top50.drop('Population', axis=1, inplace=True)
df_statsT_GDP_top50.drop('GDP', axis=1, inplace=True)
df_statsT_GDP_top50.drop('MtCO2perGDP', axis=1, inplace=True)
df_statsT_GDP_top50.drop('MtCO2perPop', axis=1, inplace=True)

df_statsT_GDP_top50.head(10)

,CoalperGDP,OilperGDP,GasperGDP,GFperGDP,CementperGDP
Country,,,,,
Zimbabwe,2.179726,0.515006,0.000000,0.000000,0.105163
Trinidad and Tobago,NaN,0.129088,1.174685,0.000000,0.008880
Turkmenistan,NaN,0.273426,0.735869,0.000000,0.010831
Libya,0.000000,0.635857,0.214448,0.056311,0.019194
Mongolia,0.693737,0.132184,0.000000,0.000000,0.004951
Uzbekistan,0.069986,0.061498,0.673293,0.000000,0.024292
South Africa,0.682099,0.113717,0.015585,0.000000,0.009938
Ukraine,0.382004,0.097563,0.242634,0.000702,0.010199
Bosnia and Herzegovina,0.555689,0.145556,0.015752,0.000000,0.014384
Russian Federation,0.161470,0.147078,0.369954,0.016484,0.013224

In [30]:
df_statsT_Pop_top50.head(10)

,Coal,Oil,Gas,Gas flaring,Cement,MtCO2,Population,GDP,MtCO2perGDP,MtCO2perPop,CoalperPop,OilperPop,GasperPop,GFperPop,CementperPop
Country,,,,,,,,,,,,,,,
Qatar,NaN,18.7181,77.7081,1.07360,2.19250,99.69230,2172065,268825.0328,0.370845,45.897475,NaN,8.617652,35.776139,0.494276,1.009408
Trinidad and Tobago,NaN,4.5913,41.7803,0.00000,0.31583,46.68743,1354483,35567.2420,1.312653,34.468819,NaN,3.389707,30.845939,0.000000,0.233174
Kuwait,NaN,61.4813,38.8138,0.41770,1.12120,101.83400,3753121,246261.8250,0.413519,27.133151,NaN,16.381380,10.341740,0.111294,0.298738
Brunei Darussalam,0.00000,1.9922,7.3231,0.49098,0.11750,9.92378,417394,24965.7076,0.397496,23.775569,0.000000,4.772948,17.544814,1.176299,0.281509
United Arab Emirates,6.51160,50.4780,131.3254,1.89060,8.00050,198.20610,9086139,510644.2176,0.388149,21.814117,0.716652,5.555495,14.453378,0.208075,0.880517
Saudi Arabia,0.00000,382.4539,188.0931,0.00000,31.39460,601.94160,30886545,1360519.6709,0.442435,19.488797,0.000000,12.382541,6.089807,0.000000,1.016449
Luxembourg,0.27276,7.5070,2.3802,0.00000,0.37486,10.53482,556573,38521.6342,0.273478,18.928011,0.490070,13.487898,4.276528,0.000000,0.673515
Bahrain,0.00000,4.8197,20.2362,0.00000,0.43266,25.48856,1361930,52577.4765,0.484781,18.715029,0.000000,3.538875,14.858473,0.000000,0.317682
United States of America,1730.62290,2280.2022,1451.8760,13.09680,38.96450,5514.76240,319448634,14794170.9227,0.372766,17.263378,5.417531,7.137931,4.544944,0.040998,0.121974
Oman,0.00000,19.0051,46.6563,1.76600,2.33210,69.75950,4236057,141674.8773,0.492391,16.468027,0.000000,4.486507,11.014087,0.416897,0.550536

In [31]:
df_statsT_Pop_top50.drop('Coal', axis=1, inplace=True)
df_statsT_Pop_top50.drop('Oil', axis=1, inplace=True)
df_statsT_Pop_top50.drop('Gas', axis=1, inplace=True)
df_statsT_Pop_top50.drop('Gas flaring', axis=1, inplace=True)
df_statsT_Pop_top50.drop('Cement', axis=1, inplace=True)
df_statsT_Pop_top50.drop('MtCO2', axis=1, inplace=True)
df_statsT_Pop_top50.drop('Population', axis=1, inplace=True)
df_statsT_Pop_top50.drop('GDP', axis=1, inplace=True)
df_statsT_Pop_top50.drop('MtCO2perGDP', axis=1, inplace=True)
df_statsT_Pop_top50.drop('MtCO2perPop', axis=1, inplace=True)

df_statsT_Pop_top50.head(10)

,CoalperPop,OilperPop,GasperPop,GFperPop,CementperPop
Country,,,,,
Qatar,NaN,8.617652,35.776139,0.494276,1.009408
Trinidad and Tobago,NaN,3.389707,30.845939,0.000000,0.233174
Kuwait,NaN,16.381380,10.341740,0.111294,0.298738
Brunei Darussalam,0.000000,4.772948,17.544814,1.176299,0.281509
United Arab Emirates,0.716652,5.555495,14.453378,0.208075,0.880517
Saudi Arabia,0.000000,12.382541,6.089807,0.000000,1.016449
Luxembourg,0.490070,13.487898,4.276528,0.000000,0.673515
Bahrain,0.000000,3.538875,14.858473,0.000000,0.317682
United States of America,5.417531,7.137931,4.544944,0.040998,0.121974
Oman,0.000000,4.486507,11.014087,0.416897,0.550536

In [434]:
#Convert to csv
#df_statsT_MtCO2_top50.to_csv('MtCO2_byCountry.tsv', sep='\t')
#df_statsT_GDP_top50.to_csv('MtCO2perGDP_byCountry.tsv', sep='\t')
#df_statsT_Pop_top50.to_csv('MtCO2perPop_byCountry.tsv', sep='\t')

In [32]:
#INTERSECTION OF ALL THREE COUNTRY SETS
intersection_3measures = df_statsT_MtCO2_top50.index.intersection(df_statsT_GDP_top50.index).intersection(df_statsT_Pop_top50.index)
print intersection_3measures
print 'size of intersection: ' + repr(len(intersection_3measures))

Index([u'United Arab Emirates', u'Saudi Arabia', u'United States of America',
       u'Australia', u'Canada', u'North America', u'Oceania', u'South Korea',
       u'Kazakhstan', u'Russian Federation', u'South Africa', u'Malaysia',
       u'Iran', u'Poland', u'Middle East', u'China', u'Venezuela'],
      dtype='object', name=u'Country')
size of intersection: 17

In [33]:
#UNION OF ALL THREE COUNTRY SETS
union_3measures = df_statsT_MtCO2_top50.index.union(df_statsT_GDP_top50.index).union(df_statsT_Pop_top50.index)
print union_3measures
print 'size of union: ' + repr(len(union_3measures))

Index([u'Africa', u'Algeria', u'Argentina', u'Asia', u'Australia', u'Austria',
       u'Bahrain', u'Belarus', u'Belgium', u'Bosnia and Herzegovina',
       u'Brazil', u'Brunei Darussalam', u'Bulgaria', u'Canada',
       u'Central America', u'China', u'Cyprus', u'Czech Republic', u'Denmark',
       u'EU28', u'Egypt', u'Equatorial Guinea', u'Estonia', u'Europe',
       u'Finland', u'France', u'Germany', u'Greece', u'Iceland', u'India',
       u'Indonesia', u'Iran', u'Iraq', u'Ireland', u'Israel', u'Italy',
       u'Jamaica', u'Japan', u'Jordan', u'KP Annex B', u'Kazakhstan',
       u'Kuwait', u'Kyrgyzstan', u'Libya', u'Luxembourg',
       u'Macedonia (Republic of)', u'Malaysia', u'Malta', u'Mexico',
       u'Middle East', u'Mongolia', u'Montenegro', u'Netherlands',
       u'New Zealand', u'Non KP Annex B', u'Non-OECD', u'North America',
       u'Norway', u'OECD', u'Oceania', u'Oman', u'Pakistan', u'Palau',
       u'Poland', u'Qatar', u'Russian Federation', u'Saudi Arabia', u'Serbia',
       u'Seychelles', u'Slovenia', u'South Africa', u'South America',
       u'South Korea', u'Spain', u'Statistical Difference', u'Taiwan',
       u'Thailand', u'Trinidad and Tobago', u'Turkey', u'Turkmenistan',
       u'Ukraine', u'United Arab Emirates', u'United Kingdom',
       u'United States of America', u'Uzbekistan', u'Venezuela', u'Viet Nam',
       u'World', u'Zimbabwe'],
      dtype='object', name=u'Country')
size of union: 89